import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
const { chromium } = await import(process.env.SMITHNAV_PLAYWRIGHT_MODULE || '@playwright/test');
const base = process.env.SMITHNAV_TEST_URL || 'http://localhost:8788';
if (!['localhost', '127.0.0.1'].includes(new URL(base).hostname)) throw new Error('Browser tests are restricted to localhost.');
const token = process.env.SMITHNAV_TEST_SETUP_TOKEN;
if (!token) throw new Error('Set SMITHNAV_TEST_SETUP_TOKEN for a fresh local database.');
const initialized = (await (await fetch(base + '/api/status')).json()).initialized;
const existing = initialized ? JSON.parse(await readFile('test-results/local-test-account.json', 'utf8')) : null;
if (existing && (existing.username !== 'local_admin' || existing.note !== 'LOCAL TEST ONLY; never deployed')) throw new Error('This database is not a known browser-test fixture.');
const password = existing?.password || 'Local-' + crypto.randomUUID();
await mkdir('test-results', { recursive: true });
await writeFile('test-results/local-test-account.json', JSON.stringify({ note: 'LOCAL TEST ONLY; never deployed', username: 'local_admin', password }, null, 2), { mode: 0o600 });
const browser = await chromium.launch({ headless: true, ...(process.env.SMITHNAV_BROWSER_PATH ? { executablePath: process.env.SMITHNAV_BROWSER_PATH } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(base);
  if (!initialized) {
  await page.getByLabel('初始化密钥').fill(token);
  await page.getByLabel('用户名', { exact: true }).fill('local_admin');
  await page.getByLabel('显示名称', { exact: true }).fill('Smith');
  await page.getByLabel('密码', { exact: true }).fill(password);
  await page.getByRole('button', { name: '创建管理员账号' }).click();
  await page.getByRole('heading', { name: '欢迎回来', exact: true }).waitFor();
  }
  await page.getByLabel('用户名', { exact: true }).fill('local_admin');
  await page.getByLabel('密码', { exact: true }).fill(password);
  await page.getByRole('button', { name: '登录导航空间' }).click();
  await page.getByRole('heading', { name: /Smith/ }).waitFor();
  if (initialized) {
    await page.evaluate(async () => {
      const send = async (path, method, data = {}) => { const response = await fetch('/api' + path, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!response.ok) throw new Error(await response.text()); };
      const board = await (await fetch('/api/board')).json();
      for (const group of board.groups) await send('/groups/' + group.id, 'DELETE');
      const images = await (await fetch('/api/images')).json();
      for (const image of images.images) await send('/images/' + image.id, 'DELETE');
      const users = await (await fetch('/api/users')).json();
      for (const user of users.users.filter(user => user.username === 'local_reader')) await send('/users/' + user.id, 'DELETE');
      await send('/groups', 'POST', { title: '常用网站' });
    });
    await page.reload(); await page.getByRole('heading', { name: /Smith/ }).waitFor();
  }
  await page.getByRole('button', { name: '添加导航', exact: true }).click();
  await page.getByLabel('网站名称').fill('Cloudflare');
  await page.getByLabel('网站地址').fill('https://dash.cloudflare.com');
  await page.getByLabel('描述（选填）').fill('连接每一种可能');
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jBf8AAAAASUVORK5CYII=', 'base64');
  await page.getByRole('tab', { name: '图片', exact: true }).click();
  await page.locator('#link-upload').setInputFiles({ name: 'test-logo.png', mimeType: 'image/png', buffer: png });
  await page.locator('#selected-image-name').filter({ visible: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('#selected-image-name').value === 'test-logo.webp');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('heading', { name: 'Cloudflare', exact: true }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: 'Cloudflare', exact: true }).waitFor();
  const imageStatus = await page.locator('.card-anchor img').evaluate(async image => { await image.decode(); return image.naturalWidth; });
  assert.equal(imageStatus, 1);
  await page.getByRole('button', { name: '管理导航', exact: true }).click();
  await page.getByRole('button', { name: '编辑 Cloudflare', exact: true }).click();
  await page.getByLabel('网站名称').fill('Cloudflare Dashboard');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('heading', { name: 'Cloudflare Dashboard' }).waitFor();
  await page.locator('.floating-tools').getByRole('button', { name: '完成编辑', exact: true }).click();

  // Seed only the local test account through the authenticated API for layout inspection.
  await page.evaluate(async () => {
    const send = async (path, data) => { const response = await fetch('/api' + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!response.ok) throw new Error(await response.text()); return response.json(); };
    const board = await (await fetch('/api/board')).json();
    await send('/links', { title: 'GitHub', url: 'https://github.com', description: '代码与灵感的交汇处', icon: '⌘', group_id: board.groups[0].id });
    await send('/links', { title: 'Notion', url: 'https://www.notion.so', description: '记录、整理，让想法发生', icon: 'N', group_id: board.groups[0].id });
    const design = await send('/groups', { title: '设计与灵感', sort_order: 10 });
    for (const [title, url, description, icon] of [['Figma', 'https://www.figma.com', '从想法到设计', 'F'], ['Dribbble', 'https://dribbble.com', '发现全世界的设计灵感', '◉'], ['Behance', 'https://www.behance.net', '优秀作品与创意故事', 'Bē']]) await send('/links', { title, url, description, icon, group_id: design.id });
    const tools = await send('/groups', { title: '日常工具', sort_order: 20 });
    for (const [title, url, description, icon] of [['Google', 'https://www.google.com', '探索你想知道的一切', 'G'], ['YouTube', 'https://www.youtube.com', '看见更大的世界', '▶'], ['Wikipedia', 'https://www.wikipedia.org', '自由的知识百科', 'W']]) await send('/links', { title, url, description, icon, group_id: tools.id });
  });
  await page.reload();
  await page.getByRole('heading', { name: 'Wikipedia', exact: true }).waitFor();
  await page.getByRole('button', { name: '搜索导航', exact: true }).click();
  await page.getByRole('searchbox', { name: '搜索导航', exact: true }).fill('代码');
  assert.equal(await page.locator('.link-card').count(), 1);
  await page.getByRole('searchbox', { name: '搜索导航', exact: true }).fill('');
  await page.getByRole('button', { name: '设计与灵感', exact: true }).click();
  assert.equal(await page.locator('.link-card').count(), 3);
  await page.getByRole('button', { name: '全部导航', exact: true }).click();
  await page.getByRole('button', { name: '收起搜索', exact: true }).click();
  await page.locator('#toast').evaluate(el => el.classList.remove('visible'));
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '系统应用', exact: true }).click();
  await page.getByRole('button', { name: '分组管理', exact: true }).click();
  await page.getByRole('button', { name: '新建分组', exact: true }).click();
  await page.getByLabel('分组名称').fill('浏览器测试分组');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const groupRow = page.getByRole('row').filter({ hasText: '浏览器测试分组' });
  await groupRow.getByRole('button', { name: '编辑分组' }).click();
  await page.getByLabel('分组名称').fill('浏览器测试分组已更新');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('row').filter({ hasText: '浏览器测试分组已更新' }).getByRole('button', { name: '删除分组' }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await page.getByText('浏览器测试分组已更新', { exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '用户管理', exact: true }).click();
  await page.getByRole('button', { name: '添加用户', exact: true }).click();
  await page.getByLabel('用户名', { exact: true }).fill('local_reader');
  await page.getByLabel('显示名称', { exact: true }).fill('测试用户');
  await page.getByLabel('初始密码').fill(password);
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByText('@local_reader', { exact: true }).waitFor();
  await page.locator('#toast').evaluate(el => el.classList.remove('visible'));
  await page.screenshot({ path: 'test-results/users.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '图片库', exact: true }).click();
  await page.getByRole('button', { name: '删除图片', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await page.locator('.error').filter({ hasText: '图片正在被导航使用' }).waitFor();
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: /^我的导航/ }).click();
  await page.getByRole('heading', { name: /Smith/ }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('#management').isVisible(), false);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile layout overflows');
  await page.locator('#toast').evaluate(el => el.classList.remove('visible'));
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '管理导航', exact: true }).click();
  await page.getByRole('button', { name: '删除 Wikipedia', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await page.getByRole('heading', { name: 'Wikipedia', exact: true }).waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: '系统应用' }).click();
  await page.getByRole('button', { name: '退出登录', exact: true }).click();
  await page.getByLabel('用户名', { exact: true }).fill('local_reader');
  await page.getByLabel('密码', { exact: true }).fill(password);
  await page.getByRole('button', { name: '登录导航空间' }).click();
  await page.getByRole('heading', { name: 'SmithNav', exact: true }).waitFor();
  assert.equal(await page.locator('.link-card').count(), 0);
  await page.getByRole('button', { name: '系统应用', exact: true }).click();
  await page.getByRole('heading', { name: '账号设置', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '用户管理', exact: true }).count(), 0);
  await page.getByRole('button', { name: '关闭系统应用', exact: true }).click();
  assert.deepEqual(errors, []);
  await writeFile('test-results/local-test-account.json', JSON.stringify({ note: 'LOCAL TEST ONLY; never deployed', username: 'local_admin', password }, null, 2), { mode: 0o600 });
  console.log('Browser smoke passed: setup, login, CRUD, D1 compressed upload/render, reload persistence, user creation, search, filters, image protection, mobile, account isolation.');
} catch (error) {
  await page.screenshot({ path: 'test-results/browser-failure.png', fullPage: true });
  console.error('Page errors:', errors);
  console.error('Visible page:', await page.locator('body').innerText());
  throw error;
} finally { await browser.close(); }
